name = "NREL"
uuid = "c59c93cf-786b-4daa-a9b1-85200e0302ff"
repo = "https://github.nrel.gov/JuliaLang/NRELRegistry"
description = "Registry for internal or otherwise-unpublished NREL Julia packages"

[packages]
"e9572c70-259d-42a9-812a-bf29f717e3f1" = { name = "CapacityValue", path = "CapacityValue"}
"62286e6e-1779-56f1-888a-1c0056788ce0" = { name = "MinCostFlows", path = "MinCostFlows"}
"23000632-8e99-4af6-adcc-f1f915ea3706" = { name = "PLEXOS2PRAS", path = "PLEXOS2PRAS"}
"05348d26-1c52-11e9-35e3-9d51842d34b9" = { name = "PRAS", path = "PRAS"}
"f1bff6d7-bd5f-4f25-88ac-02781f2d51b7" = { name = "ResourceAdequacy", path = "ResourceAdequacy"}


